Edit.README.md
noncover222kdy/chat-space pull request #1
Opened 2019-02-26 09:13 UTC by noncover222kdy

2019-02-26 10:11 UTC, ghost requested changes

2019-02-26 10:11 UTC, hiroki5123 commented on README.md
> +|group_name|string|null: false, unique: false|
nameでいいかと思います

2019-02-26 10:11 UTC, hiroki5123 commented on README.md
> +|image|string|
アソシエーションに関するカラムが２つ足りません

2019-02-26 10:11 UTC, hiroki5123 commented on README.md
> +|Column|Type|Options|
ここのテーブルは中間テーブルですので、必要なカラムを見直してみましょう

2019-02-26 11:20 UTC, noncover222kdy commented on README.md
> +|group_name|string|null: false, unique: false|
nameに変更しました

2019-02-26 11:21 UTC, noncover222kdy commented on README.md
> +|image|string|
アソシエーションに関するカラムのuser_idとgroup_idを追加しました

2019-02-26 11:21 UTC, noncover222kdy commented on README.md
> +|Column|Type|Options|
user_idとgroup_idを定義し直しました

2019-02-27 06:02 UTC, miyagit approved these changes
LGTMです。

2019-02-27 06:03 UTC, merged